### ISSUE TITLE
TypeError: Cannot read property '1' of null @callerPath

### ISSUE THREAD

**Issue by LukasWillin** [sultan99/sexy-require#3]
Good evening Sultan

When I exitedly went to try your small utility I came across this weird error which I cant figure out. Though it should be noted, that it could just be the ignorance of a newbie:

### Test Project Structure
I made a small test project with the following structure
```
/static/path
   /index.js
   /base.js
   /sub
      /sub.js
```
### index.js
``` js
require("sexy-require");
const sub = require("/sub/sub");
// I tried "/static/path/sub/sub(.js)" with and without '.js' & "sub.js" "sub"
console.log(sub);
```
### sub/sub.js
``` js
const base = require("/base");
// // I tried "/static/path/base(.js)" with and without '.js' & "base.js" "base"
module.exports = base;
```
### base.js
``` js
module.exports = "check mate";
```

### Execution
After running "> node ./static/path/index.js" from within the project root folder I get the following error:
``` js
TypeError: Cannot read property '1' of null
    at callerPath (C:\Users\[username]\Documents\[prjname]\Static Paths Test\node_modules\sexy-require\index.js:41:29)
    at getRoot (C:\Users\[username]\Documents\[prjname]\Static Paths Test\node_modules\sexy-require\index.js:52:22)
    at rootPath (C:\Users\[username]\Documents\[prjname]\Static Paths Test\node_modules\sexy-require\index.js:59:14)
    at Module.require (C:\Users\[username]\Documents\[prjname]\Static Paths Test\node_modules\sexy-require\index.js:84:30)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\[username]\Documents\[prjname]\Static Paths Test\static\path\index.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
I did not create & configure a .paths file since it is optional.
The idea was to 'console.log' the string "check mate" as set in 'base.js' which is required via 'sub/sub.js' in 'index.js'.
So the require chain would be index.js > sub/sub.js > base.js.

But this did not work for said TypeError.

Can you point me to the cause? Did I do something wrong (very probable) or is it sexy-require (probably not)?

Cheers and kind regards
Lukas Willin

**Comment by sultan99** [comment]
Hi @LukasWillin, there was an issue with node v10. 
What version is your nodejs?
You should declare `require("sexy-require");` once in index file.

**Comment by sultan99** [comment]
I have fixed the bug, install latest version **v1.1.2**

Example [you can check here ](https://repl.it/@sultan99/usage-example-of-sexy-require)

**Comment by LukasWillin** [comment]
I will try once im home :) Ill report back to you once i had time to check it out!

**Comment by LukasWillin** [comment]
Okay so first things first: I have npm version 6.10.3. But Ill try your updated version first before I update that.
Okay so now it doesnt seem to find the sub.js (/sub/sub) anymore though the error is gone.
``` js
Error: Cannot find module '/sub/sub'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Module.require (C:\Users\l.willin\Documents\MSC\Static Paths Test\node_modules\sexy-require\index.js:90:18)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\l.willin\Documents\MSC\Static Paths Test\static\path\index.js:6:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
Ill update my node version now and try again.

**Comment by LukasWillin** [comment]
So I updated to the current LTS Version 8.12.0 but to no avail: Still cant find the sub.js module
``` js
Error: Cannot find module '/sub/sub'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (C:\Users\l.willin\Documents\MSC\Static Paths Test\node_modules\sexy-require\index.js:90:18)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\l.willin\Documents\MSC\Static Paths Test\static\path\index.js:6:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```
Is sexy-require dependent on Node 11.0.0 ?

**Comment by LukasWillin** [comment]
Allright silly me ... More or less.
I was expecting sexy-require to use the index.js location as the root folder. Error is gone and all modules are found. :)
Thank you for the fix and your time helping a newbie out. Really a great package! Now I can get rid of all those pesky requires.

Cheers!
